approve_by_comment: true
approve_regex: '(A|a)pproved|\+1'
reject_regex: '(R|r)ejected|-1'
reject_value: -1
reset_on_push: true
reviewers:
  name: default
  members:
    - Driesboy
    - Sandertv
  required: 2
